<?xml version="1.0" ?>
<map version="1.9.13">
    <node TEXT="Sample Mind Map" ID="ID_968593da_15e4_4e7b_aa8e_04d72b4113d0">
        <richcontent TYPE="NOTE" CONTENT-TYPE="xml/">
            <html>
                <head/>
                <body>
                    <p>Generated by MockLLMAdapter</p>
                </body>
            </html>
        </richcontent>
        <node TEXT="First Topic" ID="ID_0bbbcdb7_29a9_4c4d_9100_409ecb5e6c4d" POSITION="right">
            <richcontent TYPE="NOTE" CONTENT-TYPE="xml/">
                <html>
                    <head/>
                    <body>
                        <p>First topic note</p>
                    </body>
                </html>
            </richcontent>
        </node>
        <node TEXT="Second Topic" ID="ID_0924c3b5_9823_4375_8549_d3f01686ad6f" POSITION="left">
            <richcontent TYPE="NOTE" CONTENT-TYPE="xml/">
                <html>
                    <head/>
                    <body>
                        <p>Second topic note</p>
                    </body>
                </html>
            </richcontent>
        </node>
    </node>
</map>
