<?xml version="1.0" ?>
<map version="1.9.13">
    <node TEXT="Sample Mind Map" ID="ID_dc01b32d_5bd3_4d44_b53d_1f8b54e58172">
        <richcontent TYPE="NOTE" CONTENT-TYPE="xml/">
            <html>
                <head/>
                <body>
                    <p>Generated by MockLLMAdapter</p>
                </body>
            </html>
        </richcontent>
        <node TEXT="First Topic" ID="ID_5111f2ca_522b_4e83_a9d7_1a37f54a99f7" POSITION="right">
            <richcontent TYPE="NOTE" CONTENT-TYPE="xml/">
                <html>
                    <head/>
                    <body>
                        <p>First topic note</p>
                    </body>
                </html>
            </richcontent>
        </node>
        <node TEXT="Second Topic" ID="ID_0efaebb1_f74e_4ac0_9774_3cd9b6ab6489" POSITION="left">
            <richcontent TYPE="NOTE" CONTENT-TYPE="xml/">
                <html>
                    <head/>
                    <body>
                        <p>Second topic note</p>
                    </body>
                </html>
            </richcontent>
        </node>
    </node>
</map>
